export const PrivacyPolicyContent = {
  hero: {
    title: "Privacy Policy",
    sections: [
      {
        title: "",
        descriptions: [
          "Ordrio Technologies Private Limited (“us”, “we”, or “our”) operates the ordrio.com website and the Ordrio mobile application (herein after referred to as the “Service”). Our Privacy Policy explains how we collect, use, disclose, and protect information that applies to our Service, and your choices about the collection and use of your information. This policy sets out how Ordrio collects and uses the information that we collect about you when you use the Ordrio services. This policy also explains the choices that you can make about the way that we use your information.",
          "By using the Website and/or registering yourself at ordrio.com you authorize us to contact you via email or phone call or SMS and offer you our services, imparting product knowledge, offer promotional offers running on the website & offers offered by the associated third parties, for which reasons, personally identifiable information may be collected. And irrespective of the fact that you have also registered yourself under DND or DNC or NCPR service, you still authorize us to give you a call from Ordrio for the above-mentioned purposes till 365 days of your registration with us.",
        ],
      },
      {
        title: "Definitions",
        descriptions: [
          "Personal Data: Personal Data means data about a living individual who can be identified from those data.",
          "Usage Data: Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself.",
          "Cookies: Cookies are small pieces stored on your device (computer or mobile device). You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.",
        ],
      },
      {
        title: "Use of Data",
        descriptions: [
          "Ordrio Technologies Private Limited uses the collected data for various purposes: To provide and maintain our Service. To notify you about changes to our Service. To allow you to participate in interactive features of our Service when you choose to do so. To provide customer support. To gather analysis or valuable information so that we can improve our Service. To monitor the usage of our Service. To detect, prevent and address technical issues. To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information.",
        ],
      },
      {
        title: "Retention of Data",
        descriptions: [
          "Ordrio Technologies Private Limited will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies. Ordrio Technologies Private Limited will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.",
        ],
      },
      {
        title: "Transfer of Data",
        descriptions: [
          "Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. Ordrio Technologies Private Limited will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.",
        ],
      },
      {
        title: "Deletion of Data",
        descriptions: [
          "You can request deletion of your Personal Data directly by deleting your account within your Account section. If you are unable to perform this action yourself, you can contact us at  contact@ordrio.com",
          "Disclosure for Law Enforcement",
          "Under certain circumstances, Ordrio Technologies Private Limited may be required to disclose your Content if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).",
        ],
      },
      {
        title: "Legal Requirements",
        descriptions: [
          "Ordrio Technologies Private Limited may disclose your Personal Data in the good faith belief that such action is necessary to: To comply with a legal obligation. To protect and defend the rights or property of Ordrio Technologies Private Limited. To prevent or investigate possible wrongdoing in connection with the Service. To protect the personal safety of users of the Service or the public. To protect against legal liability.",
        ],
      },
      {
        title: "Security of Data",
        descriptions: [
          "The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.",
        ],
      },
      {
        title: "Contact Us",
        descriptions: [
          "For any questions about this Privacy Policy, please contact us at contact@ordrio.com",
        ],
      },
    ],
  },
};
